insert into Team (TeamName) values ('Banjar Danginsema');
insert into Team (TeamName) values ('Xiasha');
insert into Team (TeamName) values ('Minji');
insert into Team (TeamName) values ('Yong’an');
insert into Team (TeamName) values ('Osekovo');
insert into Team (TeamName) values ('Saari');
insert into Team (TeamName) values ('Tanguiéta');
insert into Team (TeamName) values ('Wenchang');
insert into Team (TeamName) values ('Taiyang');
insert into Team (TeamName) values ('Aş Şaff');
insert into Team (TeamName) values ('Tudela');
insert into Team (TeamName) values ('Jilib');
insert into Team (TeamName) values ('Masons Bay');
insert into Team (TeamName) values ('La Cruz');
insert into Team (TeamName) values ('Jiangfang');
insert into Team (TeamName) values ('Dagup');
insert into Team (TeamName) values ('Beidao');
insert into Team (TeamName) values ('Rabāţ-e Sangī-ye Pā’īn');
insert into Team (TeamName) values ('Sâmraông');
insert into Team (TeamName) values ('Chimtāl');
insert into Team (TeamName) values ('Lordegān');
insert into Team (TeamName) values ('Charata');
insert into Team (TeamName) values ('Hrvace');
insert into Team (TeamName) values ('Badajoz');
insert into Team (TeamName) values ('Arsenal');
insert into Team (TeamName) values ('Kayukembang');
insert into Team (TeamName) values ('Comodoro Rivadavia');
insert into Team (TeamName) values ('Guamo');
insert into Team (TeamName) values ('Shijing');
insert into Team (TeamName) values ('Duayaw Nkwanta');
insert into Team (TeamName) values ('Salgado');
insert into Team (TeamName) values ('Kumalarang');
insert into Team (TeamName) values ('São José do Rio Preto');
insert into Team (TeamName) values ('Santa María de Ipire');
insert into Team (TeamName) values ('Georgetown');
insert into Team (TeamName) values ('Apongo');
insert into Team (TeamName) values ('Menanga');
insert into Team (TeamName) values ('Smach Mean Chey');
insert into Team (TeamName) values ('Rixinhe');
insert into Team (TeamName) values ('San José El Ídolo');
insert into Team (TeamName) values ('Baldone');
insert into Team (TeamName) values ('Yingchuan');
insert into Team (TeamName) values ('Paracambi');
insert into Team (TeamName) values ('Colorado Springs');
insert into Team (TeamName) values ('Lívingston');
insert into Team (TeamName) values ('Jaworzynka');
insert into Team (TeamName) values ('Kangān');
insert into Team (TeamName) values ('Puyang');
insert into Team (TeamName) values ('Rengat');
insert into Team (TeamName) values ('Garbolovo');
insert into Team (TeamName) values ('Khvalovo');
insert into Team (TeamName) values ('Port-de-Paix');
insert into Team (TeamName) values ('Maulawin');
insert into Team (TeamName) values ('Shuitou');
insert into Team (TeamName) values ('Sonzacate');
insert into Team (TeamName) values ('Custódia');
insert into Team (TeamName) values ('Santa Maria');
insert into Team (TeamName) values ('Shuangshi');
insert into Team (TeamName) values ('Grevená');
insert into Team (TeamName) values ('Yao');
insert into Team (TeamName) values ('Haukivuori');
insert into Team (TeamName) values ('San Ignacio');
insert into Team (TeamName) values ('Caujul');
insert into Team (TeamName) values ('Bugembe');
insert into Team (TeamName) values ('Katrineholm');
insert into Team (TeamName) values ('Sidi Bousber');
insert into Team (TeamName) values ('Vamvakoú');
insert into Team (TeamName) values ('Pavia');
insert into Team (TeamName) values ('Triwil');
insert into Team (TeamName) values ('Gąbin');
insert into Team (TeamName) values ('Partikan');
insert into Team (TeamName) values ('Cirangga Kidul');
insert into Team (TeamName) values ('San Rafael Arriba');
insert into Team (TeamName) values ('Shuyuan');
insert into Team (TeamName) values ('Veguitas');
insert into Team (TeamName) values ('Tegalrejo');
insert into Team (TeamName) values ('Finote Selam');
insert into Team (TeamName) values ('Bacem');
insert into Team (TeamName) values ('Paita');
insert into Team (TeamName) values ('Zhongguan');
insert into Team (TeamName) values ('Trondheim');
insert into Team (TeamName) values ('Piraí do Sul');
insert into Team (TeamName) values ('Laholm');
insert into Team (TeamName) values ('Abbotsford');
insert into Team (TeamName) values ('Zhangjiafang');
insert into Team (TeamName) values ('Susunan');
insert into Team (TeamName) values ('San Antonio');
insert into Team (TeamName) values ('Banjar Tibubiyu Kaja');
insert into Team (TeamName) values ('Yanjiang');
insert into Team (TeamName) values ('Temara');
insert into Team (TeamName) values ('Kiruna');
insert into Team (TeamName) values ('Camrose');
insert into Team (TeamName) values ('Bieniewice');
insert into Team (TeamName) values ('Francisco I Madero');
insert into Team (TeamName) values ('Santa Maria');
insert into Team (TeamName) values ('Nikísiani');
insert into Team (TeamName) values ('Boston');
insert into Team (TeamName) values ('Shangtianba');
insert into Team (TeamName) values ('Halle');
insert into Team (TeamName) values ('Srebrenica');
